In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('weight.csv')
data.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [3]:
data.isnull().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [4]:
data.shape

(500, 4)

In [5]:
data['Gender'] = data.Gender.apply(lambda x: 1 if x == "Male" else 0)

In [6]:
data.head()

Gender  Height  Weight  Index
0       1     174      96      4
1       1     189      87      2
2       0     185     110      4
3       0     195     104      3
4       1     149      61      3

In [7]:
X = data.drop('Index', axis=1)
X.head()

Gender  Height  Weight
0       1     174      96
1       1     189      87
2       0     185     110
3       0     195     104
4       1     149      61

In [8]:
Y = data.Index
Y.head()

0    4
1    2
2    4
3    3
4    3
Name: Index, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [11]:
model = LinearRegression().fit(X_train, Y_train)
model.score(X_test, Y_test)

0.7962929261018074

In [14]:
model.predict(X_test)

array([4.00042305, 2.35182455, 3.25757795, 3.28935721, 4.09980251,
       6.01906252, 4.73630207, 5.63107258, 3.10299365, 5.82847118,
       3.64836074, 4.40777202, 1.89479948, 4.43947187, 4.69633276,
       2.80201508, 6.05634566, 4.90894203, 2.89304327, 5.16442014,
       2.30908967, 5.99284168, 1.53994432, 3.65522254, 3.8913392 ,
       5.32453559, 5.79265024, 6.26204098, 4.32076064, 2.45683944,
       4.1771071 , 5.44603967, 3.98938802, 3.64554302, 3.31557805,
       2.12543954, 4.79158873, 2.42785303, 3.15963582, 2.26896154,
       4.76946412, 1.9762797 , 3.84575933, 3.06291766, 4.93795572,
       3.23553275, 3.29209551, 3.21346028, 3.47577292, 3.44125535,
       3.92452612, 3.75741731, 1.86307477, 1.73189117, 5.79126745,
       2.51890849, 2.60722324, 6.06046675, 6.54232986, 4.052892  ,
       4.1509384 , 5.353522  , 4.34416377, 3.91761218, 1.48750265,
       2.31456868, 3.09193134, 3.62208777, 2.15719153, 2.11437723,
       2.17655056, 4.0943235 , 2.16540884, 3.17891544, 5.78709

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
model1 = RandomForestRegressor().fit(X_train, Y_train)

In [17]:
model1.predict(X_test)

array([4.85, 2.04, 3.63, 3.85, 4.27, 5.  , 5.  , 5.  , 3.5 , 5.  , 3.9 ,
       5.  , 1.55, 4.66, 5.  , 2.64, 5.  , 5.  , 3.  , 5.  , 1.32, 5.  ,
       1.22, 4.  , 4.21, 5.  , 5.  , 5.  , 4.97, 1.98, 4.37, 5.  , 4.02,
       4.  , 3.66, 1.87, 5.  , 2.02, 3.58, 2.11, 4.97, 1.71, 4.  , 3.19,
       5.  , 3.9 , 3.71, 3.47, 3.72, 3.7 , 4.8 , 4.51, 1.83, 1.03, 5.  ,
       2.7 , 2.83, 5.  , 5.  , 4.04, 4.9 , 5.  , 4.45, 4.52, 0.47, 2.11,
       3.29, 4.  , 1.91, 1.99, 1.91, 4.53, 1.99, 3.66, 5.  , 5.  , 5.  ,
       3.99, 2.37, 4.99, 5.  , 3.09, 2.06, 5.  , 3.99, 5.  , 3.26, 4.95,
       4.27, 2.44, 1.04, 1.89, 5.  , 3.69, 5.  , 1.78, 5.  , 4.68, 1.26,
       4.98])

In [19]:
model1.score(X_test, Y_test)

0.9562944954679152

In [21]:
model1.predict([[1, 174, 96]])

array([3.71])

In [22]:
import joblib

In [24]:
joblib.dump(model1, 'bmi.pkl')

['bmi.pkl']